CREATE TABLE APL_EFD.TAB_EFD_0002 (
	ID NUMBER(11,0) DEFAULT apl_efd.seq_tab_efd_0002_id.nextval ,
	TAB_EFD_0000_ID NUMBER(11,0),
	CLAS_ESTAB_IND CHAR(2),
	CONSTRAINT PK_TAB_EFD_0002 PRIMARY KEY (ID),
	CONSTRAINT FK_TAB_EFD_0002_0000 FOREIGN KEY (TAB_EFD_0000_ID) REFERENCES APL_EFD.TAB_EFD_0000(ID) ON DELETE CASCADE
);

CREATE TABLE APL_EFD.TAB_EFD_C191 (
    ID NUMBER(11,0) DEFAULT apl_efd.seq_tab_efd_C191_id.nextval ,
    TAB_EFD_C190_ID NUMBER(11,0),
    VL_FCP_OP NUMBER(2),
    VL_FCP_ST NUMBER,
    VL_FCP_RET NUMBER,

    CONSTRAINT PK_TAB_EFD_C191 PRIMARY KEY (ID),
    CONSTRAINT FK_TAB_EFD_C191_C190 FOREIGN KEY (TAB_EFD_C190_ID) REFERENCES APL_EFD.TAB_EFD_C190(ID) ON DELETE CASCADE
);